databases:
  - name: basecamp2productiondb
    databaseName: basecamp2productiondb
    user: my_basecamp2
    plan: free

services:
  - type: web
    name: my_basecamp2
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # Uncomment below if you're on a paid plan to run migration before starting the app
    # preDeployCommand: "bundle exec rails db:migrate"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: basecamp2productiondb
          property: connectionString
      - key: RAILS_MASTER_KEY
        value: your-actual-master-key
      - key: WEB_CONCURRENCY
        value: 2
